import express from "express";
import portfolioRoutes from "../modules/portfolio/portfolio.routes.js";
import galleryRoutes from "../modules/gallery/gallery.routes.js";
import mediaRoutes from "../modules/media coverage/media.routes.js";
import testimonialRoutes from "../modules/testimonials/testimonial.routes.js";
import faqRoutes from "../modules/FAQ/faq.routes.js";
import blogRoutes from "../modules/blogs/blog.routes.js";
import careerRoutes from "../modules/career/job.routes.js";
import resumeRoutes from "../modules/resume/resume.routes.js";
import userRoutes from "../modules/users/user.routes.js";   
import seoRoutes from "../modules/seo/seo.routes.js";
import pageSEORoutes from "../modules/pageSEO/pageSEO.routes.js";
import redirectRoutes from "../modules/redirects/redirect.routes.js";
import websiteSettingsRoutes from "../modules/websiteSettings/wensiteSettings.routes.js";
import analyticsRoutes from "../modules/analytics/analytics.routes.js";
import adminRoutes from "../modules/admin/admin.routes.js";
import founderJourneyRoutes from "../modules/founderJourney/founderJourney.routes.js";
import activityLogRoutes from "../modules/activityLog/activityLog.routes.js";
import homepageRoutes from "../modules/homepage/homepage.routes.js";
import aboutRoutes from "../modules/about/about.routes.js";
import collaborationRoutes from "../modules/collabration/collaboration.routes.js";
import { campaignRoutes, launchRoutes } from "../modules/campaign/campaigns.routes.js";
import eventsRoutes from "../modules/events/events.routes.js";
import whatWeDoRoutes from "../modules/whatWeDo/whatWeDo.routes.js";
import servicesRoutes from "../modules/service/service.routes.js";
import MissionVisionRoutes from "../modules/missionVision/missionVision.routes.js";
import contactRoutes from "../modules/contact/contact.routes.js";
import uploadRoutes from "../modules/upload/upload.routes.js";

const router = express.Router();

router.use("/portfolio", portfolioRoutes);
router.use("/gallery", galleryRoutes);
router.use("/testimonials", testimonialRoutes);
router.use("/faq", faqRoutes);
router.use("/media-coverage", mediaRoutes);
router.use("/blogs", blogRoutes);
router.use("/career", careerRoutes);
router.use("/resume", resumeRoutes);
router.use("/users", userRoutes);
router.use("/seo", seoRoutes);
router.use("/page-seo", pageSEORoutes);
router.use("/redirects", redirectRoutes);
router.use("/website-settings", websiteSettingsRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/admin", adminRoutes);
router.use("/founder-journey", founderJourneyRoutes);
router.use("/logs", activityLogRoutes);
router.use("/homepage", homepageRoutes);
router.use("/about", aboutRoutes);
router.use("/collaboration", collaborationRoutes);
router.use("/campaigns", campaignRoutes);
router.use("/launches", launchRoutes);
router.use("/events",eventsRoutes);
router.use("/what-we-do", whatWeDoRoutes);
router.use("/services", servicesRoutes);
router.use("/mission-vision", MissionVisionRoutes);
router.use("/contact", contactRoutes);
router.use("/upload", uploadRoutes);

export default router;